name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build or prepare artifacts
      - name: Build project
        run: |
          # Replace with your build commands
          mkdir -p artifacts
          echo "Example artifact content" > artifacts/example.txt

      # Upload artifacts as part of the release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Use the tag name that triggered the workflow
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          # token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/example.txt # Path to your artifact
          asset_name: example.txt # Name of the artifact
          asset_content_type: text/plain
